name: Python application test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version
        
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        
    - name: Initialize Conda
      shell: bash
      run: |
        conda init bash
        
    - name: Create Conda environment
      shell: bash
      run: |
        source ~/.bashrc
        conda env create --name classy_yarp --file env_linux.yaml
        
    - name: Activate Conda environment
      shell: bash
      run: |
        source ~/.bashrc
        conda activate classy_yarp
        conda info --envs
        conda list
        # Prepare pysis env
        cp .pysisyphusrc /home/runner/.pysisyphusrc
        sed -i "s|CONDA_ENV|${CONDA}|g" /home/runner/.pysisyphusrc
        
    - name: Run pytest
      run: |
               #home=$(pwd)
               echo $CONDA
               which xtb
               #which crest
               #$CONDA/bin/xtb --version
               #$CONDA/bin/crest --version
               #xtb

               # test crest #
               #cd $home/crest-test
               #$CONDA/bin/crest HGCIXCUEYOPUTN.xyz -xname -opt vtight -chrg 0 -uhf 0 -gfn2 -nozs -T 1
               #asd
               #pysis --version
               # test Organometallics
               #obabel --version
               #
               # run Organometallic YARP Example #
               #cd $home/examples/
               #pytest -s
               #cd $home/pyTEST_Example/
               # xtb and crest are in conda bin, others in pip bin
               #sed -i "s|CONDA_PATH|${CONDA}|g" test_rxn.py
               #pytest -s
      shell: bash
