name: Python application test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        conda env update --file env_linux.yaml --prune
        #if [ -f pytest_requirements.txt ]; then 
        #pip install -r pytest_requirements.txt; 
        #fi
        #export CONDA_ALWAYS_YES="true"
        #pip install 'rdkit==2024.3.5'
        #pip install 'scipy==1.11.1'
        #pip install xtb
        #pip install 'joblib==1.3.1'
        #pip install 'PyYAML==6.0.1'
        #pip install openbabel-wheel
        #pip install 'pandas==2.0.3'
        #pip install 'ase==3.22.1'
        #pip install 'xgboost==1.7.6'
        #pip install 'h5py==3.9.0'
        #pip install pysisyphus
        #conda install -y conda-forge::crest
        #pip install --force-reinstall 'scikit-learn==1.3.0'
        #pip install --force-reinstall 'numpy==1.24.4'
        #conda install -y conda-forge::xtb
        #conda install -y conda-forge::crest=2.12
        #unset CONDA_ALWAYS_YES
        pip install .
        # CHECK
        pip freeze
        # Prepare pysis env
        cp .pysisyphusrc /home/runner/.pysisyphusrc
        cond=asd
        sed -i "s|CONDA_ENV|${CONDA}|g" /home/runner/.pysisyphusrc
    - name: Run pytest
      run: |
               home=$(pwd)
               echo $CONDA
               
               whereis xtb
               whereis crest
               #$CONDA/bin/xtb --version
               #$CONDA/bin/crest --version

               ######################
               # TEST INSTALLATIONS #
               ######################
               # test crest #
               #cd $home/crest-test
               #$CONDA/bin/crest $home/crest-test/HGCIXCUEYOPUTN.xyz -xname -opt vtight -chrg 0 -uhf 0 -gfn2 -nozs -T 1
               # test pysis #
               #pysis --version
               # test Openbabel #
               #obabel --version

               ###################################
               # run Organometallic YARP Example #
               ###################################
               cd $home/examples/
               pytest -s

               ###############################
               # run YARP-xTB pytest Example #
               ###############################
               cd $home/pyTEST_Example/
               sed -i "s|CONDA_PATH|${CONDA}|g" test_rxn.py
               pytest -s
      shell: bash
